# DeltaRedis Configuration File
RedisServer:
  URL: localhost
  Port: 6379
  HasPassword: False
  Password: DeltaRedis_Is_Great!

# Name        | Type
# ------------------------
# MrRoboto    | BungeeCord
# Diamond     | Spigot
# Gold        | Spigot
# Iron        | Spigot

# Groups servers tied to one BungeeCord server.
# From the example, this should be set to 'MrRoboto'.
BungeeName: Bungee

# Name of the server as listed in BungeeCord. (Ignore for DeltaRedis on BungeeCord)
# From the example, it should be 'Diamond', 'Gold' or 'Iron'.
ServerName: World

# Used for debugging DeltaRedis
DebugMode: False
