name: DeltaRedis
main: com.gmail.tracebachi.DeltaRedis.DeltaRedisPlugin
version: 1.5
author: Trace Bachi (tracebachi@gmail.com, BigBossZee)
commands:
  runcmd:
    description: Allows the user to send commands to other servers that will get run by that server's console.
    aliases: [rc]
    permission: DeltaRedis.RunCmd
