name: DeltaRedis
main: com.gmail.tracebachi.DeltaRedis.Spigot.DeltaRedis
version: ${project.version}
authors: [Trace Bachi (tracebachi@gmail.com, BigBossZee), FarmVivi]
commands:
  deltaredisdebug:
    description: Allows the user to toggle debug logging for DeltaRedis.
    aliases: []
permissions:
  DeltaRedis.Debug:
    description: Permission to use /deltaredisdebug