name: DeltaRedis
main: com.yahoo.tracebachi.DeltaRedis.Spigot.DeltaRedisPlugin
version: 1.0
author: Trace Bachi (tracebachi@yahoo.com, BigBossZee)
commands:
 runcmd:
   description: Allows the user to send commands to other servers that will get run by that server's console.
   aliases: [rc]
   permission: DeltaRedis.runcmd
