name: DeltaRedis
main: com.gmail.tracebachi.DeltaRedis.Spigot.DeltaRedis
version: 1.6
author: Trace Bachi (tracebachi@gmail.com, BigBossZee)
commands:
  isonline:
    description: Allows the user to check if a player is online.
    aliases: [find]
    permission: DeltaRedis.IsOnline
  listall:
    description: Allows the user to check the list of players online.
    permission: DeltaRedis.ListAll
  runcmd:
    description: Allows the user to send commands to other servers that will get run by that server's console.
    aliases: [rc]
    permission: DeltaRedis.RunCmd
